name: Git Versioning

on:
  pull_request:
    types:
      - closed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Changed Files
        id: changed_files
        run: |
          git fetch
          git diff --name-only origin/main origin/${{ github.event.pull_request.head.ref }}
          CHANGED_FILES=$(git diff --name-only origin/main origin/${{ github.event.pull_request.head.ref }}) 
          echo $CHANGED_FILES
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Update Git Tags
        run: |
          git config user.name "Anthony G Thagichu"
          git config user.email "athagichu@gerties.org"
          git tag ${{ steps.version.outputs.version }}
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            This is the release for version ${{ steps.version.outputs.version }}.



            Changed Files:
            ${{ steps.changed_files.outputs.CHANGED_FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
