name: Git Versioning

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }} # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}

      - name: Update Git Tags
        run: |
          git config user.name "Anthony G Thagichu"
          git config user.email "athagichu@gerties.org"
          git tag ${{ steps.version.outputs.version }}
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Generate Change Log
        id: changelog
        run: |
          git log --pretty=format:"%h - %an, %ar : %s" ${{ steps.version.outputs.previous-version }}..${{ steps.version.outputs.version }} > changelog.txt
          echo "::set-output name=changelog::changelog.txt"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            This is the release for version ${{ steps.version.outputs.version }}.

            Commit messages for this release:
            ${{ steps.commit_messages.outputs.commit_messages }}

            Changelog:
            ${{ steps.changelog.outputs.changelog }}
          files: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
